### Get friend requests
GET http://localhost:3001/api/friendRequests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFzbyIsImlkIjoiNjUyMTNjNjEzMWI0OTlhODNlZTg5NjZjIiwiZXhwIjoxNzAxODAxNTUyLCJpYXQiOjE3MDE3OTc5NTJ9.oqjHAF88-uVm8HvmfXBdSt3ntgaRSA1KFXEHwn0FiPY